### ISSUE TITLE
MIssing libxcb-cursor

### ISSUE THREAD

**Issue by BuffaloBison** [nomic-ai/gpt4all-chat#24] opened 2023-04-14 13:24 UTC
Install on Pop!_OS 22.04 LTS:
Install appears without error.  Executing ./chat results:

blm@pop-os:/opt/gpt4/bin$ sudo chown blm:blm * && chmod 777 *
blm@pop-os:/opt/gpt4/bin$ ls -la
total 3748036
drwxrwxr-x 2 root root       4096 Apr 13 12:24 .
drwxr-xr-x 6 root root       4096 Apr 14 13:53 ..
-rwxrwxrwx 1 blm  blm    52726552 Apr 13 12:24 chat
-rwxrwxrwx 1 blm  blm  3785248281 Apr 12 03:23 ggml-gpt4all-j.bin
blm@pop-os:/opt/gpt4/bin$ ./chat
./chat: error while loading shared libraries: libxcb-cursor.so.0: cannot open shared object file: No such file or directory
eof
<<print log>>
@pop-os:/opt/gpt4$ cat InstallationLog.txt
************************************* Invoked: Fri Apr 14 13:35:06 2023
[0] Arguments: ./gpt4all-0.1.0-Linux.run
[11] Operations sanity check succeeded.
[13] Using metadata cache from "/home/blm/.cache/qt-installer-framework/0973be00-4d7e-3bb7-a6fa-28e764f3a340"
[13] Found 0 cached items.
[13] Language: en-US
[4960] Fetching latest update information...
[5487] Retrieving meta information from remote repository...
[5691] Extracting meta information...
[5697] Updating local cache with 1 new items...
[5925] Loading component scripts...
[23588] Selected components without dependencies:
gpt4all
[23590] Installation space required: "3.86 GB" Temporary space required: "3.17 GB" Local repository size: "0.00 bytes"
[23592] Cache and install directories are on the same volume. Volume mount point: "/" Free space available: "413.63 GB"
[25114] backup  operation: Mkdir
[25114] 	- arguments: /opt/gpt4
[25115] Done
[25115] perform  operation: Mkdir
[25115] 	- arguments: /opt/gpt4
[25115] Done
[25115] Fallback: "/home/blm/Downloads/gpt4all-0.1.0-Linux.run --start-server PRODUCTION,/tmp/{dcb31162-fe8f-48cc-9b2e-717c690ea055},{532293a4-4fad-45a8-8e3e-5adfe0d8ca0d}"
[30499] perform  operation: Mkdir
[30499] 	- arguments: /opt/gpt4
[30524] Done
[30526] Preparing the installation...
[30526] Install size: 1 components
[30527] Downloading packages...
[30528] Downloading archive "0.1.0bin.7z.sha1" for component gpt4all.
[30881] Downloading archive "0.1.0bin.7z" for component gpt4all.
[587154] Downloading archive "0.1.0lib.7z.sha1" for component gpt4all.
[587546] Downloading archive "0.1.0lib.7z" for component gpt4all.
[589627] Downloading archive "0.1.0content.7z.sha1" for component gpt4all.
[589970] Downloading archive "0.1.0content.7z" for component gpt4all.
[590413] Preparing to unpack components...
[590420] backup gpt4all concurrent operation: Extract
[590420] 	- arguments: installer://gpt4all/0.1.0content.7z, /opt/gpt4
[590420] Started
[590420] backup gpt4all concurrent operation: Extract
[590420] 	- arguments: installer://gpt4all/0.1.0bin.7z, /opt/gpt4
[590420] Started
[590421] backup gpt4all concurrent operation: Extract
[590421] 	- arguments: installer://gpt4all/0.1.0lib.7z, /opt/gpt4
[590421] Started
[590437] Unpacking components...
[590438] perform gpt4all concurrent operation: Extract
[590438] 	- arguments: installer://gpt4all/0.1.0bin.7z, /opt/gpt4
[590438] Started
[590438] perform gpt4all concurrent operation: Extract
[590438] 	- arguments: installer://gpt4all/0.1.0lib.7z, /opt/gpt4
[590438] Started
[590439] perform gpt4all concurrent operation: Extract
[590439] 	- arguments: installer://gpt4all/0.1.0content.7z, /opt/gpt4
[590439] Started
[1085573] Installing component gpt4all
[1085579] backup gpt4all operation: CreateDesktopEntry
[1085579] 	- arguments: /usr/share/applications/GPT4AllChat.desktop, Type=Application
Terminal=false
Exec="/opt/gpt4/bin/chat"
Name=GPT4All-Chat
Icon=/opt/gpt4/logo-48.png
Name[en_US]=GPT4All-Chat
[1085582] Done
[1085582] perform gpt4all operation: CreateDesktopEntry
[1085582] 	- arguments: /usr/share/applications/GPT4AllChat.desktop, Type=Application
Terminal=false
Exec="/opt/gpt4/bin/chat"
Name=GPT4All-Chat
Icon=/opt/gpt4/logo-48.png
Name[en_US]=GPT4All-Chat
[1085624] Done
[1085625] backup gpt4all operation: Copy
[1085625] 	- arguments: /usr/share/applications/GPT4AllChat.desktop, /home/blm/Desktop/GPT4AllChat.desktop
[1085627] Done
[1085628] perform gpt4all operation: Copy
[1085628] 	- arguments: /usr/share/applications/GPT4AllChat.desktop, /home/blm/Desktop/GPT4AllChat.desktop
[1085934] Done
[1085935] backup gpt4all operation: License
[1085935] 	- arguments:
[1085935] Done
[1085935] perform gpt4all operation: License
[1085935] 	- arguments:
[1085974] Done
[1086075] Writing maintenance tool: "/opt/gpt4/maintenancetool.new"
[1086076] Writing maintenance tool.
[1091510] Wrote permissions for maintenance tool.
[1092224] Maintenance tool hard restart: false.
[1092228] Installation finished!
************************************* Invoked: Fri Apr 14 14:05:08 2023
[0] Arguments: /opt/gpt4/maintenancetool
[23] Operations sanity check succeeded.
[25] Using metadata cache from "/home/blm/.cache/qt-installer-framework/0973be00-4d7e-3bb7-a6fa-28e764f3a340"
[25] Found 1 cached items.
[26] Language: en-US
[8304] Fetching latest update information...
[13138] Fetching latest update information...
[13165] Loading component scripts...
eof eom

**Comment by gmy77** [comment] 2023-04-14 13:30
[https://stackoverflow.com/questions/38478029/platform-plugin-libqxcb-so-found-but-can-not-find-qt-libs-deploying-qt-applica](url)

**Comment by manyoso** [comment] 2023-04-14 13:57
https://github.com/nomic-ai/gpt4all-chat/issues/3 duplicate of solved issue

**Closed by manyoso** 2023-04-14 13:57 UTC
