### ISSUE TITLE
INTEL Mac problem... MacOS: Bin does not run on this system (intel mac not supported yet)

### ISSUE THREAD

**Issue by flutterrausch** [nomic-ai/gpt4all-chat#15] opened 2023-04-14 09:07 UTC
Installer successful, generated Applications/gpt4all/bin/gpt4all.app "does not run on system":

16" MacbookPro 2019 (Intel i7)
Ventura 13.2.1

I guess it only runs on M1/M2?

Names of files and error message are similar from what I remember (already deleted everything).

**Comment by afloch2000** [comment] 2023-04-14 10:12
Yes I have the same issue. Could someone confirm the HW requirements for Mac?

**Comment by manyoso** [comment] 2023-04-14 11:28
Confirmed that the installer doesn't support Intel macs yet. Actively working on it.

**Comment by flutterrausch** [comment] 2023-04-14 11:33
Please note on the download, it's 3GB ;-)

**Comment by manyoso** [comment] 2023-04-17 20:58
Closing as this is duplicate of another one and almost solved.

**Closed by manyoso** 2023-04-17 20:58 UTC

**Comment by flutterrausch** [comment] 2023-04-17 23:39
Um. Is it solved or not? When? Neither download, nor other tickets give a hint.
