### ISSUE TITLE
I've installed latest version, but my mac says it cant open chat.app, cuz it's not supported

### ISSUE THREAD

**Issue by erkinov-wtf** [nomic-ai/gpt4all-chat#47] opened 2023-04-15 23:55 UTC
You can’t open the application “chat.app” because this application is not supported on this Mac.

this is the modal, whenever i try to open chat.app

my macos version - 13.3.1 (22E261)

**Comment by Critical11** [comment] 2023-04-16 15:46
Needs a darwin-x64-ver

**Comment by erkinov-wtf** [comment] 2023-04-16 16:10
> Needs a darwin-x64-ver

ok, where i can download that version?

**Comment by Critical11** [comment] 2023-04-16 16:32
Looks like a darwin-x64-ver not been released as yet...

**Comment by davidldennison** [comment] 2023-04-17 01:15
Having the same issue on macOS Monterey Version 12.6.6.

**Comment by ncklboy** [comment] 2023-04-17 18:15
Same. iMac Pro running Ventura.

**Comment by manyoso** [comment] 2023-04-17 21:01
Closing as this is a dupe of many others and fix is imminent.

**Closed by manyoso** 2023-04-17 21:01 UTC
