### ISSUE TITLE
How to improve gpt4all-chat or how to expand its knowledge?

### ISSUE THREAD

**Issue by ccartermices** [nomic-ai/gpt4all-chat#58] opened 2023-04-17 07:01 UTC
I have installed gpt4all on my win10 computor. However, it reapeated "I don't know" when I asked it some questions (but the questions in github's example can work). How to improve gpt4all-chat or how to expand its knowledge?

**Comment by behhzadd** [comment] 2023-04-17 09:52
I have win 10 on my laptop but the chat.exe doesn't work.any idea to help me?

**Comment by manyoso** [comment] 2023-04-17 20:32
there will be an update soon that will greatly expand. check back in a few hours

**Comment by ch01ca** [comment] 2023-04-18 02:00
I installed windows UI and it do mot answer questions too. What's the cause?

**Comment by manyoso** [comment] 2023-04-18 12:49
Check back for updates as things are improving quickly. Closing for now as it is to generic a task to execute on.

**Closed by manyoso** 2023-04-18 12:49 UTC
